import type { Metadata } from "next";
import { Geist, Geist_Mono, Google_Sans, Open_Sans } from "next/font/google";
import "./globals.css";
import { Cross } from "lucide-react";
import { Hospital } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${googleSans.variable} ${openSans.variable}  h-full antialiased`}
    >
      <body className="min-h-full box-border w-screen  flex flex-row ">
          <div className=" flex flex-row w-full justify-around gap-3">
        <nav className=" h-screen flex flex-row text-neutral-700 p-4 ">
            <div className="flex flex-col h-full px-2 gap-5 items-center py-6">
              {/* {"Logo"} */}
              <div className="text-2xl font-bold rounded-full text-gray-600">
                <a href="/" className="   ">
                <Hospital size={30} className="bg-slate-500 rounded-full text-white w-16 h-12 cursor-pointer hover:rounded-full hover:bg-slate-700"/>
                </a>
              </div>
              {/* {Navigation Links} */}
              <div className="rounded-4xl h-full text-slate-50 bg-slate-800 w-18 items-center flex flex-col  justify-center space-y-6 self-center my-auto">
                <a href="" className="hover:text-slate-500">Home</a>
                <a href="" className="hover:text-slate-500">About</a>
                <a href="" className="hover:text-slate-500">Services</a>
                <a href="" className="hover:text-slate-500">Contact</a>
                <br />
                <a href="" className="hover:text-slate-500">Sign Up</a>

                {/* <a href="" className="hover:text-blue-500"></a> */}

              </div>
            </div>

          </nav>
          

        {children}
          
        </div>
      </body>
    </html>
  );
}
